#!/bin/python3

import argparse
import ai.play as play
import ai.replay as replay
import ai.train as train

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Snake AI utility script")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Command: load
    load_parser = subparsers.add_parser("load", help="Load and run saved AI")
    load_parser.add_argument("file", help="Path to saved AI file")
    load_parser.add_argument("-n", type=int, default=1, help="Number of simulations")
    load_parser.add_argument("--visual", action="store_true", help="Enable visual display")

    # Command: replay
    replay_parser = subparsers.add_parser("replay", help="Replay from saved replay file")
    replay_parser.add_argument("file", help="Path to replay file")
    replay_parser.add_argument("episode", type=int, help="Path to replay file", default=-1)

    # Command: train
    train_parser = subparsers.add_parser("train", help="Train new AI and save progress")
    train_parser.add_argument("filename", help="Path to save training results")
    train_parser.add_argument("--visual", action="store_true", help="Enable visual display")

    args = parser.parse_args()

    if args.command == "load":
        for i in range(args.n):
            size = play.play(args.file, args.visual)

            print(f"[{i + 1}] Final size : {size}")
    elif args.command == "replay":
        replay.play_replay(args.file, args.episode)
    elif args.command == "train":
        train.train(args.filename)
