#  Rewards
RED_APPLE_REWARD = -20
GREEN_APPLE_REWARD = 75
GAMEOVER_REWARD = -100
EAT_NOTHING_REWARD = -1

#  Display
RED_APPLE_CHAR = "~"
GREEN_APPLE_CHAR = "@"
WALL_CHAR = "*"
SNAKE_HEAD_CHAR = "#"
SNAKE_SEGMENT_CHAR = "o"
SPEED = 0.3

# AI Train
EPISODES = 2000
ALPHA = 0.2
GAMMA = 0.9
EPSILON = 1.0  # 1.0 == 100%
EPSILON_DECAY = 0.995  # Set 1.0 for an EPSILON strategy
EPSILON_MIN = 0.01

# World
HEIGHT = 10
WIDTH = 10
